Repository mitre/multiscanner, pull requests merged in 2018-04, with the labels that each got.

#116 Delete corresponding report in ES when deleting a task
  storage/elasticsearch_storage.py
  tests/test_api.py
  tests/test_elasticsearch.py
  utils/api.py
  utils/celery_worker.py
Labels: bug, distributed

#81 Add STIX2 output capability to multiscanner
  requirements.txt
  setup.py
  tests/utils/stix2_generator/sample_report.json
  tests/utils/stix2_generator/test_stix2_generator.py
  utils/api.py
  utils/stix2_generator/__init__.py
  web/templates/report.html
Labels: distributed, enhancement

#109 feature/metricbeat cleanup
  requirements.txt
  storage/elasticsearch_storage.py
  utils/celery_worker.py
Labels: distributed, enhancement

#112 Add new tab for system information
  multiscanner.py
  setup.cfg
  web/app.py
  web/templates/about.html
  web/templates/layout.html
  web/templates/system-health.html
Labels: distributed, enhancement, web

#125 Add presentations to docs page
  docs/index.rst
  docs/presentations.rst
Labels: docs, enhancement
